import {
  NAV_ITEM_TYPE_COLLAPSE,
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_TITLE,
} from "@/constants/navigation.constant"
import type { NavigationTree } from "@/@types/navigation"

const adminAuthority = ["admin"]

const navigationConfig: NavigationTree[] = [
  {
    key: "dashboard",
    path: "/home",
    title: "داشبورد",
    translateKey: "",
    icon: "dashboard",
    type: NAV_ITEM_TYPE_ITEM,
    authority: adminAuthority,
    subMenu: [],
  },
  {
    key: "management",
    path: "",
    title: "مدیریت سامانه",
    translateKey: "",
    icon: "",
    type: NAV_ITEM_TYPE_TITLE,
    authority: adminAuthority,
    subMenu: [
      {
        key: "users",
        path: "/users",
        title: "کاربران",
        translateKey: "",
        icon: "users",
        type: NAV_ITEM_TYPE_ITEM,
        authority: adminAuthority,
        subMenu: [],
      },
      {
        key: "finance",
        path: "",
        title: "امور مالی",
        translateKey: "",
        icon: "finance",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: adminAuthority,
        subMenu: [
          {
            key: "finance.transactions",
            path: "/finance/transactions",
            title: "تراکنش‌های کیف پول",
            translateKey: "",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: adminAuthority,
            subMenu: [],
          },
          {
            key: "finance.ledger",
            path: "/finance/ledger",
            title: "دفتر درآمد و هزینه",
            translateKey: "",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: adminAuthority,
            subMenu: [],
          },
        ],
      },
      {
        key: "operations",
        path: "/operations",
        title: "مرکز عملیات",
        translateKey: "",
        icon: "operations",
        type: NAV_ITEM_TYPE_ITEM,
        authority: adminAuthority,
        subMenu: [],
      },
      {
        key: "tickets",
        path: "",
        title: "مدیریت تیکت‌ها",
        translateKey: "",
        icon: "tickets",
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: adminAuthority,
        subMenu: [
          {
            key: "tickets.list",
            path: "/tickets",
            title: "صف تیکت‌ها",
            translateKey: "",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: adminAuthority,
            subMenu: [],
          },
          {
            key: "tickets.departments",
            path: "/tickets/departments",
            title: "دپارتمان‌ها",
            translateKey: "",
            icon: "",
            type: NAV_ITEM_TYPE_ITEM,
            authority: adminAuthority,
            subMenu: [],
          },
        ],
      },
    ],
  },
  {
    key: "system",
    path: "",
    title: "پیکربندی",
    translateKey: "",
    icon: "",
    type: NAV_ITEM_TYPE_TITLE,
    authority: adminAuthority,
    subMenu: [
      {
        key: "settings",
        path: "/settings",
        title: "تنظیمات سامانه",
        translateKey: "",
        icon: "settings",
        type: NAV_ITEM_TYPE_ITEM,
        authority: adminAuthority,
        subMenu: [],
      },
    ],
  },
]

export default navigationConfig
