services:

  web:
    image: ghcr.io/farhadtl/dadline-web:${IMAGE_TAG:-latest}
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

  admin:
    image: ghcr.io/farhadtl/dadline-admin:${IMAGE_TAG:-latest}
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

  office:
    image: ghcr.io/farhadtl/dadline-office:${IMAGE_TAG:-latest}
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

  api:
    image: ghcr.io/farhadtl/dadline-api:${IMAGE_TAG:-latest}
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
    deploy:
      resources:
        limits:
          memory: 512M

  horizon:
    image: ghcr.io/farhadtl/dadline-api:${IMAGE_TAG:-latest}
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

  scheduler:
    image: ghcr.io/farhadtl/dadline-api:${IMAGE_TAG:-latest}
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }

  postgres:
    image: dadline-postgres:${IMAGE_TAG:-latest}
    deploy:
      resources:
        limits:
          memory: 1G

  redis:
    deploy:
      resources:
        limits:
          memory: 384M
