import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_ITEM,
  NAV_ITEM_TYPE_COLLAPSE,
} from "@/constants/navigation.constant"

import type { NavigationTree } from "@/@types/navigation"

const navigationConfig: NavigationTree[] = [
  {
    key: "pishkhan",
    path: "",
    title: "پیشخان",
    translateKey: "nav.pishkhan.pishkhan",
    icon: "groupMenu",
    type: NAV_ITEM_TYPE_TITLE,
    authority: [],
    subMenu: [
      {
        key: "pishkhan.home",
        path: "/pishkhan",
        title: "نمای کلی",
        translateKey: "nav.pishkhan.home",
        icon: "home",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "pishkhan.activity",
        path: "/pishkhan/activity",
        title: "پیگیری فعالیت‌ها",
        translateKey: "nav.pishkhan.activity",
        icon: "groupSingleMenu",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "legalServices",
    path: "",
    title: "خدمات حقوقی",
    translateKey: "nav.legalServices.legalServices",
    icon: "collapseMenu",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "legalServices.requests",
        path: "/pishkhan/service-requests",
        title: "درخواست‌های من",
        translateKey: "nav.legalServices.requests",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "legalServices.newRequest",
        path: "/pishkhan/service-requests/new",
        title: "ثبت درخواست جدید",
        translateKey: "nav.legalServices.newRequest",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "legalServices.offers",
        path: "/pishkhan/service-offers",
        title: "پیشنهادهای دریافتی",
        translateKey: "nav.legalServices.offers",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "legalServices.results",
        path: "/pishkhan/service-results",
        title: "نتایج و تحویل‌ها",
        translateKey: "nav.legalServices.results",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "legalServices.phoneConsultations",
        path: "/pishkhan/phone-consultations",
        title: "مشاوره‌های تلفنی",
        translateKey: "nav.legalServices.phoneConsultations",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "contracts",
    path: "",
    title: "قراردادها",
    translateKey: "nav.contracts.contracts",
    icon: "groupCollapseMenu",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "contracts.list",
        path: "/pishkhan/contracts",
        title: "همه قراردادها",
        translateKey: "nav.contracts.list",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "contracts.new",
        path: "/pishkhan/contracts/new",
        title: "قرارداد جدید",
        translateKey: "nav.contracts.new",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "contracts.signatures",
        path: "/pishkhan/contracts/signatures",
        title: "امضاها و دعوت‌ها",
        translateKey: "nav.contracts.signatures",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "contracts.aiAnalysis",
        path: "/pishkhan/contracts/ai-analysis",
        title: "تحلیل هوشمند",
        translateKey: "nav.contracts.aiAnalysis",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "contracts.evidenceReports",
        path: "/pishkhan/contracts/evidence-reports",
        title: "گزارش‌های اصالت",
        translateKey: "nav.contracts.evidenceReports",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "ordersAndBilling",
    path: "",
    title: "سفارش‌ها و مالی",
    translateKey: "nav.ordersAndBilling.ordersAndBilling",
    icon: "groupMenu",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "ordersAndBilling.orders",
        path: "/pishkhan/orders",
        title: "سفارش‌ها",
        translateKey: "nav.ordersAndBilling.orders",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "ordersAndBilling.wallet",
        path: "/pishkhan/wallet",
        title: "کیف پول",
        translateKey: "nav.ordersAndBilling.wallet",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "ordersAndBilling.transactions",
        path: "/pishkhan/transactions",
        title: "تراکنش‌ها",
        translateKey: "nav.ordersAndBilling.transactions",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "ordersAndBilling.subscriptions",
        path: "/pishkhan/subscriptions",
        title: "اشتراک‌ها",
        translateKey: "nav.ordersAndBilling.subscriptions",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "ordersAndBilling.giftCards",
        path: "/pishkhan/gift-cards",
        title: "کارت هدیه",
        translateKey: "nav.ordersAndBilling.giftCards",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "legalTools",
    path: "",
    title: "ابزارهای حقوقی",
    translateKey: "nav.legalTools.legalTools",
    icon: "singleMenu",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "legalTools.dadbot",
        path: "/pishkhan/dadbot",
        title: "دادبات",
        translateKey: "nav.legalTools.dadbot",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "legalTools.questions",
        path: "/pishkhan/questions",
        title: "پرسش‌های حقوقی",
        translateKey: "nav.legalTools.questions",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "legalTools.lawLibrary",
        path: "/pishkhan/law-library",
        title: "کتابخانه قوانین",
        translateKey: "nav.legalTools.lawLibrary",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "legalTools.documents",
        path: "/pishkhan/legal-documents",
        title: "اسناد و نمونه‌ها",
        translateKey: "nav.legalTools.documents",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "support",
    path: "",
    title: "پشتیبانی و پیام‌ها",
    translateKey: "nav.support.support",
    icon: "collapseMenu",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "support.messages",
        path: "/pishkhan/messages",
        title: "پیام‌ها",
        translateKey: "nav.support.messages",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "support.tickets",
        path: "/pishkhan/tickets",
        title: "تیکت‌های پشتیبانی",
        translateKey: "nav.support.tickets",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "support.notifications",
        path: "/pishkhan/notifications",
        title: "اعلان‌ها",
        translateKey: "nav.support.notifications",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
  {
    key: "account",
    path: "",
    title: "حساب کاربری",
    translateKey: "nav.account.account",
    icon: "home",
    type: NAV_ITEM_TYPE_COLLAPSE,
    authority: [],
    subMenu: [
      {
        key: "account.profile",
        path: "/pishkhan/profile",
        title: "پروفایل",
        translateKey: "nav.account.profile",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "account.signature",
        path: "/pishkhan/profile/signature",
        title: "امضای من",
        translateKey: "nav.account.signature",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "account.verification",
        path: "/pishkhan/profile/verification",
        title: "احراز هویت",
        translateKey: "nav.account.verification",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
      {
        key: "account.preferences",
        path: "/pishkhan/settings/notifications",
        title: "تنظیمات اعلان‌ها",
        translateKey: "nav.account.preferences",
        icon: "",
        type: NAV_ITEM_TYPE_ITEM,
        authority: [],
        subMenu: [],
      },
    ],
  },
]

export default navigationConfig
